# Generated by Django 5.1.4 on 2025-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='User_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=100),
        ),
    ]
